version: "3.7"
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/household_accounts:/usr/src/app
      - node_modules:/usr/src/app/node_module
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true

volumes:
  node_modules: