version: "3.7"
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/usr/src/frontend/app
      - node_modules:/usr/src/frontend/app/node_module
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
  backend:
    build: ./backend
    volumes:
      - ./backend/src/:/var/www/html
  web:
    build: ./web
    ports:
      - 8081:80
    depends_on:
      - backend
    volumes:
      - ./backend/src/:/var/www/html
volumes:
  node_modules: